### ISSUE TITLE
This DOI prefix is currently inactive.

### ISSUE THREAD

**Issue by LTEnjoy** [microsoft/protein-sequence-models#14]
Hi!
I want to use the dataset provided in your paper but found that url https://doi.org/10.1234/mifst would lead to an error **This DOI prefix is currently inactive.** Could you please solve that? Thx for your help in advance!

**Comment by yangkky** [comment]
Where are you seeing that url? The correct DOI is https://zenodo.org/record/6573779#.YqjXT-zMI-Q, which I see in the readme.

**Comment by LTEnjoy** [comment]
I saw it in your paper on biorxiv.
![image](https://user-images.githubusercontent.com/52776915/200458769-e85f7e7c-2b96-47e1-8795-6475429de437.png)

**Comment by yangkky** [comment]
Ok I will package that with a few other things and upload a revision soon.
Thanks for pointing that out!

**Comment by yangkky** [comment]
This is fixed in the newest preprint.
