### ISSUE TITLE
Are the omega, theta and phi angles corresponding to the main chain torsion angles omega, psi and phi angles?

### ISSUE THREAD

**Issue by Wenhao-Jin** [microsoft/protein-sequence-models#7]
Hi authors, I am trying to use your MIF-ST model and now preparing the node/edge features. Just to be sure I got the features correctly, I was wondering if the omega, theta and phi angles in your paper are referring to the torsion angles that are used in peptide/protein structure (definitions can be found [here](https://swissmodel.expasy.org/course/text/chapter1.htm)). 

According to Figure 2 in your [MIF paper](https://www.biorxiv.org/content/10.1101/2022.05.25.493516v1.full.pdf), the answer is no. But the Figure 2 was a bit confusing to me since the omega, theta and phi are all related to the beta carbons. However, not all of the amino acids have beta carbons. I also checked the paper from Ingraham et al. (2019) which is cited in your MIF paper for this part. In that paper they didn't give much details but used the terms "omega", "psi" and "phi".  Could you help me with this? Great thanks in advance!

**Comment by yangkky** [comment]
Yes, they are the standard definitions. We use the same method for
calculating them from structure as Ingraham. Thanks for pointing out that
the figure is wrong: I'll work on fixing that.

**Comment by Wenhao-Jin** [comment]
Got you. Thanks for clarifying it, @yangkky!

**Comment by hyeh20** [comment]
@Wenhao-Jin Just wanted to clarify on this - the angle features used follows the angles described by the [trRosetta](https://www.pnas.org/doi/full/10.1073/pnas.1914677117) paper and unconventional compared to how dihedral angles for proteins are typically defined.

**Comment by Wenhao-Jin** [comment]
@hyeh20 Thank you so much for the clarification! Just to make sure, for the dist value, I was also wondering if MIF also used the distance between beta carbons as trRosetta did. Besides, is there some script or package available for generating these angles. Thanks so much again!

**Comment by hyeh20** [comment]
Yes, the distance should be between beta carbons, we will update our figure in our next revision. 

For scripts on how to generate these angles: If you are starting with a pdb file for your proteins, please use the functions in pdb_utils.py. parse_PDB will generate a coordinates dictionary and then you can use process_coords to generate the angle features. These scripts were directly modified from the trRosetta paper.

**Comment by yangkky** [comment]
@Wenhao-Jin sorry for the confusion: @hyeh20 is correct. 

The parsing functions are here: https://github.com/microsoft/protein-sequence-models/blob/main/sequence_models/pdb_utils.py

**Comment by Wenhao-Jin** [comment]
Thanks so much for the help! Sorry for the delayed response, it works on my side. Really appreciate it!
